---
name: CI

on:
  push:
    branches:
      - main
      - master
      # npm version tags
      - /^v\d+.\d+.\d+(?:-(?:alpha|beta|rc)\.\d+)?/
  pull_request:
concurrency:
  group: ci-tests-${{ github.ref }}-1
  cancel-in-progress: true
env:
  CI: true

deploy:
  name: Deploy
  runs-on: ubuntu-latest
  if: github.ref == 'refs/heads/main'
  needs: [test, floating-dependencies, ember-try-required]
  steps:
    - uses: actions/checkout@v2
    - uses: volta-cli/action@v1

    - run: echo "ADDON_DOCS_VERSION_PATH=${GITHUB_REF##*/}" >> $GITHUB_ENV

    - run: echo "ADDON_DOCS_UPDATE_LATEST=true" >> $GITHUB_ENV
      if: contains(github.ref , 'main') == true

    - run: yarn install

    - name: Deploy
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
      run: yarn ember deploy production --verbose --activate
