---
name: Deploy Docs

on:
  push:
    branches:
      - master
      - /^v\d+.\d+.\d+(?:-(?:alpha|beta|rc)\.\d+)?/
  pull_request:
  workflow_dispatch:
concurrency:
  group: "pages"
  cancel-in-progress: true
env:
  CI: true
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1

      - run: echo "ADDON_DOCS_VERSION_PATH=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - run: echo "ADDON_DOCS_UPDATE_LATEST=true" >> $GITHUB_ENV
        if: contains(github.ref , 'master') == true

      - run: yarn install

      - name: Deploy
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        run: yarn ember deploy production --verbose --activate
